---
title: "Lesson3 Project"
output: html_document
---

### Import libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(xlsx)
library(ggplot2)
library(tidyr)
library(dplyr)
library(gridExtra)
```

### Data from Gapminder: GDP/capita (US$, inflation-adjusted) by World Bank
```{r}
gdp_capita <- read.csv('../Data/GDPpercapitaconstant2000US.csv')
colnames(gdp_capita)[1] <- "Country"
head(gdp_capita)
```

### Histogram of The Past Year (1970) vs. The Recent Year (2011)
```{r warning=FALSE}
p_1970 <- ggplot(aes(x = X1970), data = subset(gdp_capita, !is.na(X1960))) +
  geom_histogram(binwidth = 500, color = 'black', fill = 'red') +
  xlab("GDP/capita in 1970") +
  theme_bw(base_size = 10) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_x_continuous(limits = c(0, 55000), breaks = seq(0, 55000, 2000))

p_2011 <- ggplot(aes(x = X2011), data = subset(gdp_capita, !is.na(X1960))) +
  geom_histogram(binwidth = 500, color = 'black', fill = 'blue') +
  xlab("GDP/capita in 2011") +
  theme_bw(base_size = 10) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_x_continuous(limits = c(0, 55000), breaks = seq(0, 55000, 2000))

grid.arrange(p_1970, p_2011, ncol = 1)
```

```{r}
gdp_capita$Country[gdp_capita$X2011 > 50000 & !is.na(gdp_capita$X2011)]
```


### Countries by Growth
```{r warning=FALSE}
gdp_capita_5yr <- subset(gdp_capita, !is.na(gdp_capita$X2006) & !is.na(gdp_capita$X2011))
gdp_capita_5yr <- select(gdp_capita_5yr, matches("Country"), X2006:X2011)
gdp_capita_5yr$growth_rate <- ((gdp_capita_5yr$X2011 - gdp_capita_5yr$X2006) 
                               / gdp_capita_5yr$X2006) * 100

ggplot(aes(x = growth_rate), data = gdp_capita_5yr) +
  geom_histogram(binwidth = 1, color = 'black', fill = 'green') +
  xlab("5 Years Growth Rate") +
  theme_bw(base_size = 10) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_x_continuous(limits = c(-30, 70), breaks = seq(-30, 70, 5))
```

```{r}
summary(gdp_capita_5yr$growth_rate)
```

```{r}
gdp_capita_5yr$Country[gdp_capita_5yr$growth_rate == min(gdp_capita_5yr$growth_rate)]
```
```
[UAE GDP/capita without inflation adjustment](https://www.google.com/search?rlz=1C1CAFA_enKR676KR676&ei=muUdW5_BMtGOsQXaiKTQBA&q=UAE+gdp+per+capita&oq=UAE+gdp+per+capita&gs_l=psy-ab.3..0i67k1j0i7i30k1j0l2j0i30k1l4j0i10i30k1j0i30k1.21108.21587.0.21827.3.3.0.0.0.0.105.279.2j1.3.0....0...1c.1.64.psy-ab..0.3.279...0i7i10i30k1j0i10k1.0.ZGpxk3626Nc)
```

```{r}
gdp_capita_5yr$Country[gdp_capita_5yr$growth_rate == max(gdp_capita_5yr$growth_rate)]
```
```
[Tajikistan GDP/capita without inflation adjustment](https://www.google.com/search?rlz=1C1CAFA_enKR676KR676&ei=eOUdW6CvNIyWsgW08424CQ&q=tajikistan+gdp+per+capita&oq=tajikis&gs_l=psy-ab.3.0.0i67k1l8j0j0i67k1.28516.30091.0.33115.7.6.0.1.1.0.100.525.5j1.6.0....0...1c.1.64.psy-ab..0.7.528...35i39k1j0i131i67k1j0i131k1j0i20i264k1.0.gYM5bQ4NgHQ)
```

### Top & Bottom Countries by Growth Class
```{r warning=FALSE}
gdp_capita_5yr$class <- ifelse(gdp_capita_5yr$X2006 > 20000, "upper", "middle")
gdp_capita_5yr$class <- ifelse(gdp_capita_5yr$X2006 < 2000, "under", 
                               gdp_capita_5yr$class)

gdp_capita_5yr$class <- as.factor(gdp_capita_5yr$class)
gdp_capita_5yr$class <- factor(gdp_capita_5yr$class, 
                               levels(gdp_capita_5yr$class)[c(2, 1, 3)])

ggplot(aes(x = growth_rate, y = ..count../sum(..count..)), data = gdp_capita_5yr) +
  geom_freqpoly(aes(color = class), binwidth = 5) +
  scale_x_continuous(limits = c(-30, 70), breaks = seq(-30, 70, 5))
```

```{r}
ggplot(aes(x = class ,y = growth_rate), data = gdp_capita_5yr) +
  geom_boxplot()
```

