---
title: "lesson4_project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(gridExtra)
library(tidyr)
library(reshape2)
library(dplyr)

hourly_pay <- read.csv('../Data/indicator_hour compensation.csv')
hourly_pay$X <- NULL
hourly_pay <- hourly_pay[-35, ]
colnames(hourly_pay)[1] <- "country"

summary(hourly_pay$X1997)
```
```{r}
hourly_pay$class <- ifelse(hourly_pay$X1997 > 20, 'high', 'middle')
hourly_pay$class <- ifelse(hourly_pay$X1997 <= 5, 'low', hourly_pay$class)
```

# Histogram of Hourly Pay
```{r}
p_1980 <- ggplot(hourly_pay, aes(X1980)) +
  geom_histogram(binwidth = 3, color = 'black', fill = 'blue') +
  xlab("Hourly Pay in 1980") +
  scale_x_continuous(limits = c(0, 45), breaks = seq(0, 45, 2))

p_2006 <- ggplot(hourly_pay, aes(X2006)) +
  geom_histogram(binwidth = 3, color = 'black', fill = 'blue') +
  xlab("Hourly Pay in 2006") +
  scale_x_continuous(limits = c(0, 45), breaks = seq(0, 45, 2))

grid.arrange(p_1980, p_2006, ncol = 1)
```

# Scatter Plot by Year
```{r}
colnames(hourly_pay) <- c('country', 1980:2006, 'class')
hourly_pay <- melt(hourly_pay, id.vars = c('country', 'class'),
                           variable.name = 'year', value.name = 'hourly_pay')
hourly_pay$year <- as.numeric(hourly_pay$year) + 1980

ggplot(hourly_pay, aes(year, hourly_pay)) +
  geom_point(alpha = 1/3, color = 'red', position = position_jitter()) +
  geom_line(stat = 'summary', fun.y = mean, color = 'red') +
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = 0.1),
            linetype = 2, color = 'blue') +
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = 0.9),
            linetype = 2, color = 'blue') +
  labs(title = "Mean Hourly Pay by Year", x = "Year", y = "Hourly Pay") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_continuous(breaks = seq(1980, 2006, 1))
```
```{r}
ggplot(hourly_pay, aes(year, hourly_pay)) +
  geom_point(alpha = 1/3, color = 'red', position = position_jitter()) +
  geom_smooth(method = 'lm', color = 'blue') +
  labs(title = "Hourly Pay Trend", x = "Year", y = "Hourly Pay") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_continuous(breaks = seq(1980, 2006, 1))
```
```{r}
cor.test(hourly_pay$year, hourly_pay$hourly_pay)
```

# Conditional Means by Year
```{r}
hourly_pay_by_year <- hourly_pay %>%
  group_by(year) %>%
  summarise(hourly_pay_mean = mean(hourly_pay, na.rm = T),
            hourly_pay_median = median(hourly_pay, na.rm = T)) %>%
  arrange(year)

ggplot(hourly_pay_by_year, aes(year, hourly_pay_median)) +
  geom_line() +
  labs(title = "Median Hourly Pay", x = "Year", y = "Hourly Pay") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_continuous(breaks = seq(1980, 2006, 1))
```

# Line Plot by Pay Class
```{r}
hourly_pay_low <- hourly_pay[hourly_pay$class == 'low', ] %>%
  group_by(year) %>%
  summarise(hourly_mean = mean(hourly_pay, na.rm = T)) %>%
  arrange(year)
hourly_pay_low$class <- paste('low')

hourly_pay_middle <- hourly_pay[hourly_pay$class == 'middle', ] %>%
  group_by(year) %>%
  summarise(hourly_mean = mean(hourly_pay, na.rm = T)) %>%
  arrange(year)
hourly_pay_middle$class <- paste('middle')

hourly_pay_high <- hourly_pay[hourly_pay$class == 'high', ] %>%
  group_by(year) %>%
  summarise(hourly_mean = mean(hourly_pay, na.rm = T)) %>%
  arrange(year)
hourly_pay_high$class <- paste('high')

hourly_pay_by_class <- rbind(hourly_pay_low, 
                             hourly_pay_middle, 
                             hourly_pay_high)

ggplot(hourly_pay_by_class, aes(year, hourly_mean)) +
  geom_line(aes(color = class)) +
  labs(title = "Mean Hourly Pay by Class", x = "Year", y = "Hourly Pay") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_continuous(breaks = seq(1980, 2006, 1))
```

